vocdoni/ui-scaffold

src/components/Process/Aside.tsx, src/components/Process/View.tsx
Switch to the 'Questions' tab whenever you vote, as currently, errors cannot be accessed from the front.
closes #299
=> switch to the questions tab when voting

src/components/ProcessCreate/Settings/Advanced.tsx
Added logic in advanced settings to toggle the options 'anonymous' and 'overwrite'.
closes #297
=> toggle overwritte and anonyomus setting options

src/components/ProcessCreate/CostPreview.tsx
Fixed issue, show spinner inside the box while the cost preview is loading
closes #310
=> spinner cost inside the box

src/components/Account/EditProfile.tsx, src/components/Organization/OrganizationModalProvider.tsx, src/components/Organization/View.tsx
closes https://github.com/vocdoni/ui-components/issues/102
=> Fixes Organization data display on edit (header and view)

src/components/Process/Header.tsx
Added separation between the 'read more' button and the lower content to avoid it looking too close on mobile
=> separation in the process header on mobile

.github/workflows/pages.yml, src/router/Router.tsx, vite.config.ts
Also fixed an issue related to BASE_URL, which should be / by default if not specified, instead of an empty space (since an empty space would make relative URLs, and that's not what we want).
**Note:** to be able to use this browser router, some changes are required depending on the server you're using to host the static pages:
- Github Pages: copy your index.html to 404.html, to trick gh pages into always returning your index.html file. Also don't forget to set the proper `BASE_URL`.
- Netlify, `serve` and others: nothing required, since `BASE_URL` has been changed to `/` already
- nginx and apache: you'll have to change the config in order to make all requests be redirected to the index.html file, for nginx would be something like this:
~~~nginx
location / {
try_files $uri /index.html; …
=> Switch to browser router

src/components/ProcessCreate/Confirm/CensusSpreadsheet.tsx, src/components/ProcessCreate/Confirm/Preview.tsx
Fixed issue, added overflow-x scroll to the spreadsheet preview as the number of columns/content can be larger than the available space
closes #379
=> census spreadsheet preview overflowx scroll

src/components/ProcessCreate/Census/Token.tsx
Double-check that if the select token option is set to 'request,' do not render the token preview or value in the select
=> prevent bug census 3 select request token option

src/i18n/locales/ca.json, src/i18n/locales/en.json, src/i18n/locales/es.json
- Fixes a typo in the title of the main page (EN)
- Unifies titles between languages
- Changes the title from `Secure, verificable and transparent online voting` to `Secure, verifiable and flexible digital voting`.
Reasoning for changing the title is because transparent can be understood from verifiable, and flexible is an important component of the protocol design that appeals more users than transparent.
cc: @p4u @jpaulet @ferranrego
=> fix english typo and unify titles between languages

src/elements/Layout.tsx, src/elements/LayoutProcessCreate.tsx
Fixed issue: Text breakpoint for 'world wide voting' in md, not in sm, to display the text when there is the correct padding
=> fixed issue text world wide voting

src/components/ProcessCreate/Census/Spreadsheet/index.tsx
Fixed issue in the weighted vote checkbox, which now occupies 100% of the container, and the padding is applied to the checkbox, not the container
=>  weighted vote checkbox

src/constants/rainbow.ts, src/i18n/locales/ca.json, src/i18n/locales/en.json, src/i18n/locales/es.json, vite/features.ts
- Renamed it to be less scary
- Added better icon
- Moved to a custom group "recovery"
- Feature is now disabled by default for this login type (must define `FEATURES='{"login": ["recovery"]}'` in order to enable it)
=> Refactor private key connector

src/components/ProcessCreate/Census/Token.tsx, src/constants/index.ts, src/importmeta.d.ts, vite.config.ts
- Implement a max census size limit as env variable, by default 5000.
- Also implement buttons to the token max census size slider, to select 1%, 5% etc...
=> Implement token census max size limit

src/components/Process/Header.tsx, src/i18n/locales/ca.json, src/i18n/locales/en.json, src/i18n/locales/es.json
Fixes https://github.com/vocdoni/ui-scaffold/issues/562
Add total census size information if the census size differs from maxCensusSize. 
It has a problem when runing `yarn translations` it add a `total_census_size_tooltip_one` key, which is not needed and nor used (this case should not going to happen). @elboletaire should we take attention to it or can we ignore it?
=> Improve census info

src/components/Process/View.tsx, src/components/ProcessCreate/Census/Gitcoin/GitcoinForm.tsx, src/components/ProcessCreate/Census/Token.tsx, src/components/ProcessCreate/StepForm/CensusGitcoin.tsx, src/components/ProcessCreate/StepForm/CensusToken.tsx, src/components/ProcessCreate/Steps/Form.tsx, src/i18n/locales/ca.json, src/i18n/locales/en.json, src/i18n/locales/es.json, src/themes/default/components/Questions.ts, src/themes/onvote/components/Questions.ts
Fix #661 
From the list it fixes
=> Visual Improvements

src/components/ProcessCreate/Census/Gitcoin/StampsUnionType.tsx, src/components/ProcessCreate/Steps/Form.tsx, src/themes/default/colors.ts, src/themes/default/components/Checkbox.ts, src/themes/default/components/Tabs.ts, src/themes/onvote/colors.ts, src/themes/onvote/components/Checkbox.ts, src/themes/onvote/components/Tabs.ts
It fixes the first an issue of #661
> Improve OR/AND selector in the "Gitcoin Passport" census type. Change the current switch to the "custom radio button" Chakra component, while preserving the text change depending on the selected option:
> ![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/c2d9a730-1c3c-48ad-b03d-762f951fee5b)
=> Implement union type custom radio button

src/components/ProcessCreate/CostPreview.tsx, src/components/ProcessCreate/Steps/Confirm.tsx, src/components/ProcessCreate/Steps/Form.tsx, src/components/ProcessCreate/Steps/use-steps.tsx
It create two new states on the form:
- isLoadingCost to know when is loading cost
- notEnoughBalance to disable the confirm button when not enough balance
=> Improve create election form states

src/components/Process/Aside.tsx
It shows the votes of only the first question instead of the sum of votes for all questions.
If an election have more than one questions you expect to se number of votes emitted thinking that on the same ballot you answer all the questions. So looking only the first question results you can know how many votes are emitted
=> Fix weight visualization

src/components/Process/Header.tsx
It was a silly problem but hard to find. The div that wrapped the actions button had position: absolute from the previous layout, which caused the menu to render off-screen until you opened it for the first time
closes #668
=> fixed issue process scroll, closes #668

src/components/Auth/SignIn.tsx, src/components/Auth/SignUp.tsx, src/components/Auth/Verify.tsx, src/components/Auth/api.ts, src/components/Auth/authQueries.ts, src/components/Auth/useAuthProvider.ts, src/router/Router.tsx, src/router/SuspenseLoader.tsx
Depends on https://github.com/vocdoni/saas-backend/pull/9/ and needs https://github.com/vocdoni/ui-scaffold/pull/765
It implements the email verification page. 
- On signup page, once signup is success it shows an "verification email sent" message with a "resend email button"
- On login page if the error of the backend is that the email is not verified, it shows the "verification email sent" message with a "resend email button"
- Implements the route `/account/verify?email=${email}&code=xxxxxxx`
- Performs an automatic verification attempt using a `useEffect`
- If success redirect to `/organization`
- Else show an error
- **Resend verification mail mutation is implemented but won't work until implemented on the backend**
In addition, it implements specific considerations for dev …
=> Saas mail verification page

src/components/AccountSaas/Create.tsx, src/components/Auth/useAuthProvider.ts, src/router/Router.tsx, src/router/SaasOrganizationProtectedRoute.tsx, src/router/SignInScreen.tsx
RemoteSigner class has a little difference with the normal Signer that is that `getAddress` function is asynchronous. 
This provoked some errors when accessing protected routes causing a blink show of Create Organization view on an "already logged in  with organization account".
To fix this I created an inner auth state to check if the RemoteSigner is loaded and has an address associated to it.
Add necessary authentication states on the provider to fix blinking page bugs when login in 
- Implements specific `SaasOrganizationProtectedRoute` to do not mix logics with the old scaffol `OrganizationProtectedRoute`
- Implements needed inner auth provider based on the signer state to properly redirect to create organization page. I used a Mutation to take advantage of the states that react query …
=> Improve auth state

src/components/Auth/Verify.tsx
It adds an input text to the mail verification page to copy paste the code if the user wants to do it (instead of follow the direct link sent on the email)
=> Add mail verification code form

src/components/AccountSaas/useAccountPlan.tsx, src/components/ProcessCreate/Census/TypeSelector.tsx, src/components/ProcessCreate/Census/UnimplementedTypeSelector.tsx, src/components/ProcessCreate/Questions/useSaasVotingType.ts, src/components/ProcessCreate/Questions/useUnimplementedVotingType.ts, src/components/ProcessCreate/Questions/useVotingType.ts, src/components/ProcessCreate/SaasFooter.tsx, src/components/ProcessCreate/SaasSaveToDraft.tsx, src/components/ProcessCreate/Settings/SaasFeatures.tsx, src/components/ProcessCreate/Settings/index.tsx, src/components/ProcessCreate/StepForm/Info.tsx, src/components/ProcessCreate/StepForm/Questions.tsx, src/components/ProcessCreate/StepForm/SaasFeatures.tsx, src/components/ProcessCreate/Steps/Form.tsx, src/components/ProcessCreate/Steps/TabsPage.tsx, src/components/ProcessCreate/Steps/use-steps.tsx, src/elements/LayoutProcessCreate.tsx, src/themes/saas/components/Form.ts, src/themes/saas/components/Tabs.ts, src/themes/saas/index.ts
This PR implements some new necessary logic in order to follow new saas requirements for process creation. Related:
https://github.com/vocdoni/interoperability/issues/210
https://github.com/vocdoni/interoperability/issues/229
- Adds a footer on process creation
- Adds a store draft button
- Implement new steps when is saas
- Add saas extra features on the form 
- Mock `useAccountPlan`, simulating a call that gives for an organization which features a plan has activated.
- Add some minimum styles to try it easier
This PR **does not** implement:
- New styles
- Some buttons logics (for example save draft or upgrade plan)
- New modals
- Logic to store the election on the saas backend (this need some meetings). For now, the SDK and the remote signer are able to create an election on the …
=> Implement create process form logic

src/components/Auth/PasswordForgotForm.tsx, src/components/Auth/PasswordResetForm.tsx, src/components/Auth/SignIn.tsx, src/components/Auth/api.ts, src/components/Auth/useAuthProvider.ts, src/components/Layout/InputBasic.tsx, src/elements/account/password/index.tsx, src/elements/account/password/reset.tsx, src/elements/account/signin.tsx, src/router/routes/auth.tsx, src/router/routes/index.ts, src/theme/index.ts
Closes https://github.com/vocdoni/interoperability/issues/200
- Renamed some components for consistency
- Changed forgot route to `account/password` to reuse it for the reset (via `account/password/reset`)
- Edited the ForgotPasswordForm component to properly make expected API calls
- Created new ResetPasswordForm component to handle the password reset behavior
- Added optional email param to signin form to autofill it when trying to recover your password
- Created elements for both password reset and password forgot, moving the expected logic there
- Done the same for SignIn (creating elements/account/signin)
- InputBasic was not accepting additional props
- Added required routes
=> Password recovery flow

src/components/Dashboard/Menu/Options.tsx, src/components/Dashboard/PricingModal.tsx, src/components/Home/index.tsx, src/components/Organization/Dashboard/PricingCard.tsx, src/i18n/locales/ca.json, src/i18n/locales/en.json, src/i18n/locales/es.json, src/theme/colors.ts, src/theme/components/card.ts, src/theme/components/modal.ts
Improved pricing modal and princing card with dark mode and delete buttons variants
=> pricing modal and card

src/components/Dashboard/Menu/Options.tsx, src/components/Organization/Dashboard/ProcessesList.tsx, src/components/Organization/Dashboard/Votings.tsx, src/elements/dashboard/processes/index.tsx, src/queries/organization.ts, src/router/routes/dashboard.tsx
- Moved react-query logic for the pagination and filtering to the route's `loader` method.
- Due to the above change, the `dashboard` routes were moved back to the hook, since having them externally would have increase significantly the amount of arguments passed to the function.
- Updated the sidebar links to point to these new filters.
- Removed old limit logic in ProcessesList, since we can now limit directly via the API.
What I don't like: the empty processes list layout...
=> Processes filtering logic

src/components/ProcessCreate/Steps/Confirm.tsx, src/components/TermsAndPrivacy/Privacy.tsx, src/components/TermsAndPrivacy/Terms.tsx, src/i18n/locales/ca.json, src/i18n/locales/en.json, src/i18n/locales/es.json
=> Changed Terms and conditions translations and added missing translations

src/components/Account/Teams.tsx, src/components/Auth/useAuthProvider.ts, src/components/Dashboard/Menu/Options.tsx, src/components/Dashboard/Menu/OrganizationSwitcher.tsx, src/components/Layout/ColorModeSwitcher.tsx, src/components/Organization/Create.tsx, src/components/Organization/Edit.tsx, src/elements/dashboard/organization/create.tsx, src/queries/account.ts
- Add SignerAddress to LocalStorageKeys
- Store and retrieve signer address from localStorage
- Use stored address if available, otherwise use first address
- Clear stored address on logout
- Fixed organization type incorrectly having name and description
- Updated components due to the previous change
- Added an organization selector for people having more than one org
- Made required changes to properly change the signer between organization changes
- Updated organization creation form to properly manage multiple organizations creation
- Removed check in previous section to ensure you can always create an org, even having one already
- Move organization switcher logic to its own component
- Added button in the menu to be able to create new orgs (will be moved probably, but at least is …
=> Multiple organization support

src/components/Auth/SignUp.tsx, src/components/ProcessCreate/Confirm/Preview.tsx, src/components/ProcessCreate/Settings/Features.tsx, src/components/ProcessCreate/StepForm/Info.tsx, src/components/ProcessCreate/Steps/Confirm.tsx, src/components/ProcessCreate/Steps/Form.tsx, src/i18n/locales/ca.json, src/i18n/locales/en.json, src/i18n/locales/es.json
This uses a new `liveResults`variable which gets its value reversed into `secretUntilTheEnd` when creating a process.
Note this is only during the process creation, vochain has not (and will not) change this, so it continues being `secretUntilTheEnd` in most places.
closes #809
=> Use liveResults instead of secretUntilTheEnd

src/components/Dashboard/Menu/Options.tsx, src/components/Process/ProcessStatusFilters.tsx, src/elements/dashboard/processes/index.tsx, tsconfig.paths.json
Created a new buttongroup component to hold them inside the process list instead
=> Remove process filters from the sidebar

src/constants/index.ts
This is a trick in order to avoid a race condition that happened sometimes (< 3% of the times) for people having a wallet connected to the application. Wallets are the first thing to load when you refresh a page, because they're browser extensions. Sometimes though, the wallet may load a bit later, causing its `fetchAccount` call to be computed after the same call done by the remote signer. This caused the remote signer to be set with the wrong address only in part of the state, causing the app to crash in some points with an "Unknown account" error.
=> Cancel any previous fetchAccount calls via axios

src/theme/components/Tabs.ts
Removed the gap from the display flex and replaced it with justify-content: space-between.
=> Tabs card layout

src/theme/components/ellipsisButton.ts, src/theme/components/index.ts
closes #1275 
This is a patch, maybe we should edit the component in ui-components so that inputProps and buttonProps are passed to EllipsisButton via usePaginationPages hook in [packages/chakra-components/src/components/Pagination/Pagination.tsx](https://github.com/vocdoni/ui-components/blob/main/packages/chakra-components/src/components/Pagination/Pagination.tsx#L114-L124)
=> feat: Fix pagination buttons sizes
