- src/components/ProcessCreate/Census/Web3.tsx
Fixed issue, changed the background of the drag and drop.
closes #304
> drag and drop wallet addresses bg

- src/components/ProcessCreate/StepForm/CensusWeb3.tsx
Error resolved, clear the 'addresses error' every time we add an address.
closes #316
> clear addresses error 

- src/components/Organization/Header.tsx
- src/components/Organization/View.tsx
- src/components/Process/Aside.tsx
- src/components/Process/Header.tsx
- src/components/Process/View.tsx
- src/theme/components/Button.ts
- src/theme/components/Card.ts
- src/theme/components/SpreadSheet.ts
- org page: bg header, space election, size image and text card no elections
- aside restyle
closes #287
> prelaunch improvements checklist issues

- src/components/Process/View.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/theme/breakpoints.ts
- src/theme/colors.ts
- src/theme/components/ConfirmModal.ts
Modal confirm vote new styles as required
> confirm modal

- src/components/Process/View.tsx
- src/components/ProcessCreate/CreationProgress.tsx
- src/components/ProcessCreate/Steps/Confirm.tsx
- src/theme/components/ConfirmModal.ts
- src/theme/components/Modal.ts
- src/theme/components/SpreadSheet.ts
- src/theme/index.ts
Modals theme with generic styles
closes #323
> theme modals

- src/components/Layout/Logo.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/es.json
1- Change header, Public voting protocol to Vocdoni
2- Change translation "Votant des del 14 d'Octubre..." to  "Votació del 14 d'Octubre..."
3- Add catalan and spanish translation form.process_create.confirm.cost_description
> small changes

- src/components/Process/Aside.tsx
- src/components/Process/Header.tsx
- src/components/Process/View.tsx
Fixed issue, in the desktop breakpoint in process view, the aside was appearing outside the viewport
> fixed issue, aside breakpoint desktop

- index.html
- package.json
- vite.config.ts
- yarn.lock
> Add current commit sha to HTML (as comment)

- src/components/Process/Aside.tsx
- src/components/Process/View.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/theme/colors.ts
- src/theme/components/SpreadSheet.ts
fixed issue process view logout button color in desktop and translaton voted_description
> process view logout button and translation

- src/components/Process/Aside.tsx
- src/components/Process/View.tsx
- src/theme/components/SpreadSheet.ts
unify the information aside in mobile and desktop, removed the information about 'election date' as this information is already present in the view.
> unify the information aside in mobile and desktop

- src/theme/components/Questions.ts
Fixed an issue where when switching from mobile to desktop view, the identifier number was not visible.
> fixed issue alert link verify your vote

- src/components/Faucet/use-faucet.tsx
Should be merged at the same time as https://github.com/vocdoni/vocfaucet/pull/7
> Updated vocdoni faucet response

- src/components/ProcessCreate/Meta.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
Added a character counter from 70% onwards for meta, title, and description, and a message for reaching the maximum character limit when reaching 100%.
> maxLength meta title and description

- src/components/ProcessCreate/StepForm/CensusToken.tsx
added font weight click here in process view token base, closes #376
> token base link font weight

- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
new translations header button new voting
closes #374
> translations new voting button

- src/elements/Faucet.tsx
added mt faucet title 
closes #372
> faucet title

- src/components/ProcessCreate/CostPreview.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
Added missing translations in the "process create preview."
> preview translations

- src/components/ProcessCreate/CostPreview.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
desktop correct layout in the cost preview of the total, your own, and after creating voting
> preview cost style

- src/components/Footer/index.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
fixed issue, the footer links to the social media with the target _blank, the other links already have it
closes #388
> footer links to social media with target _blank

- src/components/Home/Voting.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/theme/components/Card.ts
Type-voting variant for the cards on the home with voting types and bottom text 'privacy should be normal'
closes #378
> type voting cards and bottom text

- src/components/Account/EditProfile.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
remove paddings, change minw md and corrected spelling error
> edit organization modal styles

- src/components/ProcessCreate/CostPreview.tsx
- src/components/ProcessCreate/Steps/Checks.tsx
added overlay modal get voc tokens in preview and center message running checks in mobile
> fixed issues get voc tokens modal and checks text in mobile

- src/components/Faucet/Claim.tsx
- src/components/Faucet/use-faucet.tsx
- src/components/ProcessCreate/CostPreview.tsx
- src/elements/Faucet.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
**ATTENTION! THIS MUST BE ACCEPTED/DEPLOYED AT THE SAME TIME AS https://github.com/vocdoni/vocfaucet/pull/10**
Google and Facebook faucet providers buttons.
> Added FB and Ggoogle. Moving params to base64 encoded "state"

- src/Providers.tsx
- src/components/Faucet/Claim.tsx
- src/components/Faucet/use-faucet.tsx
Removed not connected account in faucet
> Bugixed Signer in Providers.

- README.md
- src/router/Router.tsx
- vite.config.ts
To add custom domains, define them in a json stringified object passed to CUSTOM_ORGANIZATION_DOMAINS env var
closes #417
> Add custom organization domains overwritting homepage

- README.md
- package.json
- src/components/Account/Create.tsx
- src/components/Faucet/Claim.tsx
- src/components/ProcessCreate/CostPreview.tsx
- src/i18n/locales/en.json
- vite.config.ts
- yarn.lock
Upgraded rainbowkit-wallets
Moved FAUCET_AMOUNT to dynamic values coming from the faucet.
> Upgraded rainbowkit-wallets

- src/components/ProcessCreate/Census/Token.tsx
fixed issue when changing the chain so that the total token count above the token select updates
> fixed issue, updated total tokens census3

- src/components/ProcessCreate/CostPreview.tsx
- src/components/ProcessCreate/Steps/Form.tsx
Loading the create form draft if "state" para is there. State param is coming from the faucet oauth flow.
> Bugfix: Draft loading

- src/i18n/locales/en.json
Improved copies and solved typos and orthographic errors.
> Copies and translations

- package.json
- src/components/Account/Create.tsx
- src/components/Navbar/index.tsx
- src/components/Process/View.tsx
- src/components/ProcessCreate/Census/Spreadsheet/CensusSpreadsheetManager.ts
- src/components/ProcessCreate/Census/Spreadsheet/index.tsx
- src/components/ProcessCreate/Census/Web3.tsx
- src/components/ProcessCreate/Confirm/Preview.tsx
- src/components/ProcessCreate/CostPreview.tsx
- src/components/ProcessCreate/Settings/Advanced.tsx
- src/components/ProcessCreate/Steps/Confirm.tsx
- src/i18n/components.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- vite.config.ts
- yarn.lock
closes #355 
closes #428
closes #414
Note this pull request cannot be merged without publishing a new version of ui-components first (branch `f/anonymous-flow` in there).
> Anonymous flow changes

- src/components/Account/Create.tsx
- src/components/Faucet/use-faucet.tsx
- src/components/ProcessCreate/CostPreview.tsx
- src/elements/Faucet.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
Waiting period now is dynamic, coming from the Faucet Service
> Faucet waiting period coming from faucet backend

- src/components/Footer/FooterOnVote.tsx
- src/components/Home/BannerOnVote.tsx
- src/components/Home/Features.tsx
- src/components/Home/Roadmap.tsx
- src/components/Home/Voting.tsx
- src/elements/HomeOnVote.tsx
- src/theme/onvote/components/Card.ts
font sizes, margins and paddings in mobile view
> adapt styles mobile

- src/components/Process/Aside.tsx
- src/components/Process/View.tsx
- src/components/Process/VoteButton.tsx
Fixed issues in the aside buttons, aside footer mobile, and logout
> fixed issues aside buttons

- src/components/Home/BannerOnVote.tsx
- src/components/Home/Features.tsx
- src/components/Home/Roadmap.tsx
Adapt the homepage to have a maximum of 3 lines in headings
related #463
> home max lines 3

- .github/workflows/test.yml
- package.json
- src/components/Navbar/index.tsx
- src/components/ProcessCreate/Census/Token.tsx
- src/components/ProcessCreate/StepForm/CensusToken.tsx
Just bugfixes:
- Use ensure0x function for my org link (fixes creating `0x0x` prefixed links)
- Re-set strategySize value to steps form state, since it's used in the final Confirm preview
- Added new lint github action task (doing tsc + prettier)
> Stage upgrade 2023-12-20

- .github/workflows/netlify.yml
- .github/workflows/test.yml
- src/components/ProcessCreate/Census/Token.tsx
Bugfix related to latest census3 changes.
> Stage bugfix 2024-01-03

- src/components/Process/Aside.tsx
- src/components/Process/View.tsx
- src/theme/colors.ts
- src/theme/components/Button.ts
- src/theme/components/Questions.ts
- src/theme/components/SpreadSheet.ts
1- VoteButton component in mobile and desktop
2- Questions checkboxes
> process view

- src/components/Organization/View.tsx
- src/components/Process/Aside.tsx
- src/components/Process/Header.tsx
- src/components/Process/View.tsx
- src/components/ProcessCreate/Census/Spreadsheet/Preview.tsx
- src/components/ProcessCreate/Census/select-components.tsx
- src/components/ProcessCreate/Confirm/Preview.tsx
- src/components/ProcessCreate/CostPreview.tsx
- src/components/ProcessCreate/Steps/Confirm.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/theme/colors.ts
- src/theme/components/Link.ts
- added STATE and SCHEUDLE labels
- Reduced header right side
- Reduced election description line height
- closes #456
refs #450
> public voting

- .env.example
- .gitignore
- README.md
- package.json
- src/components/Navbar/LanguagesList.tsx
- src/components/Navbar/Menu.tsx
- src/components/Navbar/index.tsx
- src/components/ProcessCreate/Census/TypeSelector.tsx
- src/components/ProcessCreate/Confirm/Preview.tsx
- src/components/ProcessCreate/CostPreview.tsx
- src/components/ProcessCreate/Settings/Advanced.tsx
- src/components/ProcessCreate/StepForm/Censuses.tsx
- src/components/ProcessCreate/Steps/Census.tsx
- src/components/ProcessCreate/Steps/Form.tsx
- src/constants/rainbow.ts
- src/i18n/index.ts
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/importmeta.d.ts
- src/router/Router.tsx
- src/theme/components/Tabs.ts
- vite.config.ts
- yarn.lock
> Feature toggle

- src/themes/onvote/components/Questions.ts
questions alert bg
closes #495
> fixed issue questions alert bg

- src/components/Process/Header.tsx
reduces process description line height
> reduced process description line height

- src/elements/Layout.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/themes/onvote/colors.ts
aside new requirments, bg, color and voter, voters translation
> aside styles

- src/components/Navbar/index.tsx
- src/themes/default/components/Button.ts
Fixed styles issue when btn is disabled
closes #514
> fixed issue btn disabled

- src/components/Home/Features.tsx
- src/components/Home/Roadmap.tsx
- src/components/Navbar/index.tsx
- src/components/Organization/View.tsx
- src/components/Process/Aside.tsx
- src/components/Process/Header.tsx
- src/components/Process/View.tsx
- src/elements/LayoutProcessCreate.tsx
- src/themes/default/components/Button.ts
- src/themes/default/components/Footer.tsx
- src/themes/default/components/Questions.ts
- src/themes/default/components/Tabs.ts
- src/themes/default/index.ts
- src/themes/onvote/components/Questions.ts
- src/themes/onvote/index.ts
fixed all issue problems
closes #512
> responsive mobile issues

- src/components/Home/Features.tsx
- src/components/Home/Roadmap.tsx
- src/components/Navbar/index.tsx
- src/components/Organization/View.tsx
- src/components/Process/View.tsx
- src/elements/Layout.tsx
- src/themes/default/components/Footer.tsx
- src/themes/default/index.ts
- src/themes/onvote/index.ts
Fixed max width issue in content view.
> content view max width

- package.json
- src/components/Account/EditProfile.tsx
- src/components/Faucet/Claim.tsx
- src/components/Process/ActionsMenu.tsx
- src/components/ProcessCreate/CostPreview.tsx
- src/components/ProcessCreate/Steps/Checks.tsx
- src/components/ProcessCreate/Steps/Confirm.tsx
- yarn.lock
Using our copy-pasted component instead of chakra-ui's one, at least until they fix it on their side (I hope they do so 😅)
closes #522
> Fix google chrome translate "ErrorNotFound" issue

- package.json
- src/components/Account/EditProfile.tsx
- src/components/Faucet/Claim.tsx
- src/components/Home/Features.tsx
- src/components/Home/Roadmap.tsx
- src/components/Navbar/index.tsx
- src/components/Organization/View.tsx
- src/components/Process/ActionsMenu.tsx
- src/components/Process/Aside.tsx
- src/components/Process/Header.tsx
- src/components/Process/View.tsx
- src/components/ProcessCreate/CostPreview.tsx
- src/components/ProcessCreate/CreationProgress.tsx
- src/components/ProcessCreate/Steps/Checks.tsx
- src/components/ProcessCreate/Steps/Confirm.tsx
- src/elements/Layout.tsx
- src/elements/LayoutProcessCreate.tsx
- src/themes/default/colors.ts
- src/themes/default/components/Button.ts
- src/themes/default/components/Footer.tsx
- src/themes/default/components/Questions.ts
- src/themes/default/components/Tabs.ts
- src/themes/default/index.ts
- src/themes/onvote/colors.ts
- src/themes/onvote/components/Questions.ts
- src/themes/onvote/index.ts
- yarn.lock
Google chrome translate issue and style changes
> 2024-01-30 Stage upgrade

- src/components/ProcessCreate/Census/Token.tsx
- src/components/ProcessCreate/Confirm/CensusToken.tsx
- src/components/ProcessCreate/Confirm/Preview.tsx
- src/components/ProcessCreate/Settings/Advanced.tsx
- src/components/ProcessCreate/StepForm/CensusToken.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/themes/default/components/Checkbox.ts
- src/themes/onvote/colors.ts
- src/themes/onvote/components/Alert.ts
- src/themes/onvote/components/Checkbox.ts
- when advanced settings anonymous is true show disclaimer text
- show anonymous census blance accuracy in preview
> rounded census

- src/i18n/index.ts
> Set language if it doesn't match with the resolved one

- src/components/Process/Header.tsx
- src/components/Process/View.tsx
- src/components/ProcessCreate/Confirm/Preview.tsx
- src/themes/default/components/Questions.ts
- src/themes/default/index.ts
- src/themes/onvote/index.ts
Created 'md-sizes' class to modify the size of h1, h2, h2, and p in the Markdown renderings on the process view description and question. Adjusted process title size to align with Markdown sizes
> md headings and process sizes

- src/elements/LayoutProcessCreate.tsx
Fixed issue: the background of the process create should occupy the maximum screen width regardless of the maximum width of the content
> bg process create

- src/components/Account/use-account-health-tools.tsx
- src/components/Process/Aside.tsx
- src/elements/LayoutProcessCreate.tsx
Most important fix here is the vote button that wasn't visible for spreadsheet type elections.
> 2024-02-09 Stage bugfixes

- src/components/ProcessCreate/Census/Spreadsheet/CensusSpreadsheetManager.ts
- src/components/ProcessCreate/Census/Web3.tsx
- src/components/ProcessCreate/StepForm/CensusWeb3.tsx
- src/components/ProcessCreate/Steps/Confirm.tsx
> Add weighted census support to web3 addresses census strategy

- src/components/ProcessCreate/Census/Spreadsheet/CensusSpreadsheetManager.ts
- src/components/ProcessCreate/Census/Web3.tsx
- src/components/ProcessCreate/StepForm/CensusWeb3.tsx
- src/components/ProcessCreate/Steps/Confirm.tsx
refs #551
we gotta hurry up, farcasters can't wait!
> Add weighted web3 census to STG

- src/components/ProcessCreate/Steps/index.tsx
Resolved issue in mobile text by removing the text from the steps in a smaller screen size and adjusting the margin top measurements up to desktop
> Process create steps mbl

- src/components/ProcessCreate/Census/Gitcoin/GitcoinForm.tsx
- src/components/ProcessCreate/Census/Gitcoin/StampCard.tsx
- src/components/ProcessCreate/Census/Gitcoin/index.tsx
- src/components/ProcessCreate/Confirm/Census.tsx
- src/components/ProcessCreate/Confirm/CensusToken.tsx
- src/components/ProcessCreate/StepForm/CensusGitcoin.tsx
- src/components/ProcessCreate/Steps/Confirm.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
> Add Gitcoin features

- src/components/ProcessCreate/Census/Token.tsx
Set the variable DEFAULT_CENSUS_SIZE as default initial value for the slider not max value
Also add buttons of 1% and 2% for the token slider
> Fix census slider max value

- src/components/ProcessCreate/Steps/Confirm.tsx
Use the newly created strategy instead of the GPS strategy
> Fix gitcoin census creation time

- src/components/ProcessCreate/Census/Web3.tsx
- src/components/ProcessCreate/StepForm/CensusWeb3.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
> Wallet addresses census visual improvement

- src/components/ProcessCreate/Census/Token.tsx
- src/components/ProcessCreate/Census/select-components.tsx
> Get icon based on network name

- src/components/Process/Header.tsx
- src/components/ProcessCreate/Census/Gitcoin/GitcoinForm.tsx
- src/components/ProcessCreate/Census/Gitcoin/StampCard.tsx
- src/components/ProcessCreate/Census/Gitcoin/StampIcon.tsx
- src/components/ProcessCreate/Steps/Form.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
It fixes this comments https://github.com/vocdoni/ui-scaffold/pull/582#issuecomment-2021054234
It not implements the stamps visualization on the election view because it will be implemented on https://github.com/vocdoni/ui-scaffold/pull/626
> Fix gitcoin flow

- src/components/Process/Header.tsx
This fixes a little error on the share button responsiveness.
> Fix share button responsiveness

- src/components/ProcessCreate/ModalPro.tsx
Resolved the issue where 'emailjsenabled' had the 'emailjs_public_id' repeated; updated it to 'emailjs_service_id'
> emailjsEnabled issue

- src/components/ProcessCreate/Census/Gitcoin/GitcoinForm.tsx
- src/components/ProcessCreate/Census/Gitcoin/index.tsx
- src/components/ProcessCreate/Census/Token.tsx
- src/components/ProcessCreate/Confirm/CensusToken.tsx
- src/components/ProcessCreate/CostPreview.tsx
- src/components/ProcessCreate/StepForm/CensusToken.tsx
- src/components/ProcessCreate/Steps/Confirm.tsx
Added a PR we missed yesterday: 
- #636
> 2024-04 1st sprint staging missing PR

- src/components/Process/ActionsMenu.tsx
Fix https://github.com/vocdoni/ui-scaffold/issues/630
Use the chakra ui library for the election action buttons to play, pause, stop...
> Use chakra action buttons

- src/components/Process/Header.tsx
- src/components/ProcessCreate/Census/Gitcoin/StampIcon.tsx
- src/components/ProcessCreate/Steps/Confirm.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
Show stamps on the election page as suggested by @jpaulet on this comment https://github.com/vocdoni/ui-scaffold/pull/582#issuecomment-2021096267
It depends on https://github.com/vocdoni/interoperability/issues/174
> Implement show stamps

- src/components/Process/View.tsx
Place focus on the first unanswered question when voting
> Questions focus when unanswered question

- src/components/ProcessCreate/Census/MaxCensusSizeSelector.tsx
Fix https://github.com/vocdoni/ui-scaffold/issues/641
> Fix maxCensusSize input number

- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/themes/default/components/Card.ts
- src/themes/default/components/Home/Features.tsx
- src/themes/default/components/Home/Process.tsx
- src/themes/default/components/Home/Support.tsx
- src/themes/default/components/Navbar/index.tsx
New styles and translations
closes #647
> styles and translations

- src/themes/default/components/Questions.ts
- src/themes/default/index.ts
- src/themes/onvote/components/Questions.ts
- src/themes/onvote/index.ts
New sizes for MD HTML elements h1, h2, h3, li, ul, ol, p, and a, and more bottom margin for question descriptions
> md elements sizes and description mb

- src/themes/default/components/Questions.ts
- src/themes/default/index.ts
- src/themes/onvote/components/Questions.ts
- src/themes/onvote/index.ts
md elements sizes and description mb (#653)
> Merges develop a stage

- src/components/Process/Header.tsx
- src/themes/default/index.ts
- src/themes/onvote/index.ts
Process header flex basis, and added styles white-space: pre-wrap for the MD pre tag
> MD HTML pre tag

- src/components/Editor/styles.css
> editor toolbar responsive

- src/i18n/locales/ca.json
- src/i18n/locales/es.json
The missing translations for process_create.question.others in Catalan and Spanish.
> Missing translations for process_create.question.others

- .github/workflows/netlify.yml
- src/components/ProcessCreate/ModalPro.tsx
- src/components/ProcessCreate/Steps/Census.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/themes/default/components/Tabs.ts
- src/themes/onvote/components/Tabs.ts
It fixes part of #661
> - [x] Change the text of the modal:
> ![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/78e53d1b-9d9c-4644-8973-8fb029e81e03)
> By removing: "Option not available in the free plan. To use it, you need to purchase the custom project plan." and replacing by: "XXXX is a Premium feature". (for instance: `Customization is a Premium Feature` or `SMS-based census is a Premium Feature`). 
Also, change the "Or you can directly schedule one quick call (30'') with our experts to help you create your desired voting project." to "Schedule a 30-minute call with our team to discuss your voting project. We'll guide you through the process and tailor solutions to meet your specific needs."
Same text for Spanish and Catalan.
And:
> - [x] The "pro" label in the census is …
> Fix ui for pro features

- yarn.lock
Used `yarn upgrade @vocdoni/sdk`
> Bump vocdoni-sdk 8.0

- src/components/Process/Aside.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
Is blocked by https://github.com/vocdoni/ui-components/pull/163
It takes an account if is anonymous voting or encrypted until the end, showing different cases:
- Not encrypted and not anonymous. It only show the voters on case the number of votes are different to the number of voters.
- Not encrypted and anonymous
- Encrypted and not anonymous
It fixes part of https://github.com/vocdoni/ui-scaffold/issues/532
> Show voting weight

- src/components/Faucet/Claim.tsx
Flex wrap on the claim faucet buttons so they look good on mobile
> faucet claim responsive

- yarn.lock
This is to bypass the error with new encrypted metadata processes. A proper upgrade will come addressing all flow issues (like asking for the password when the process is encrypted).
> Upgrade SDK to latest git version

- src/components/Account/Create.tsx
- src/themes/default/components/Modal.ts
- src/themes/onvote/components/Modal.ts
Fix https://github.com/vocdoni/ui-scaffold/issues/544
> Review modal styles

- src/components/ProcessCreate/Steps/Confirm.tsx
This code seems to be duplicated, need to be tested
> Delete CSP Election creation duplicated code

- src/components/Process/View.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/themes/default/colors.ts
- src/themes/onvote/colors.ts
Added modal when voting (do not refresh or update the page...) for a better user experience
> voting modal

- src/themes/default/components/Footer.tsx
- src/themes/default/components/Home/Support.tsx
> footer styles

- src/components/Organization/View.tsx
- src/components/Process/CardDetailed.tsx
- src/components/Process/Header.tsx
- src/components/Process/View.tsx
- src/themes/default/components/Card.ts
- src/themes/default/font.ts
- src/themes/default/index.ts
- src/themes/onvote/components/Card.ts
- src/themes/onvote/font.ts
- src/themes/onvote/index.ts
uinified font sizes in organization and process views
> unify font sizes

- public/default/index.html
- public/onvote/index.html
- src/constants/index.ts
- src/elements/Organization/View.tsx
- src/elements/Process.tsx
- src/importmeta.d.ts
- src/use-document-title.tsx
- vite.config.ts
Fixes https://github.com/vocdoni/ui-scaffold/issues/614
It changes the document title on certain pages using the `useDocumentTitle` hook.
When the hook is unmounted it goes back to the default page title
> Change document title

- src/themes/onvote/components/Button.ts
Added the dashboard button variant for the Onvote theme.
closes #717
> onvote btn dashboard 

- src/components/Process/View.tsx
Fixed issue top padding
closes #721
> fixed issue voting modal padding

- src/themes/default/components/Card.ts
- src/themes/onvote/components/Card.ts
Issue fixed in both themes by adding styles for links
closes #724
> fixed issue links

- src/elements/Layout.tsx
- src/themes/default/colors.ts
- src/themes/default/components/Footer.tsx
fixed issue bg footer dashboard
closes #731
> fixed issue bg footer dashboard

- src/components/Organization/Dashboard/Layout.tsx
dashboard name isTruncated in the second line
closes #723
> dashboard name

- src/i18n/locales/ca.json
- src/i18n/locales/es.json
added transaltions catalan and spanish.
closes #730
> translations

- src/elements/Layout.tsx
- src/themes/default/components/Footer.tsx
Modified footer background in all dashboard views
> Modified footer background

- src/importmeta.d.ts
- src/router/Router.tsx
- vite.config.ts
To activate SAAS now you should use 
```bash
THEME=saas SAAS_URL='url' yarn dev       
```
> Implement saas url feature flag

- src/components/Auth/ForgotPassword.tsx
- src/components/Auth/SignIn.tsx
- src/components/Auth/SignUp.tsx
- src/components/Organization/Dashboard/Menu.tsx
- src/components/OrganizationSaas/Dashboard/Layout.tsx
- src/components/OrganizationSaas/Dashboard/Menu.tsx
- src/elements/LayoutAuth.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/router/Router.tsx
> saas translations

- src/components/AccountSaas/Create.tsx
- src/components/Auth/Password.tsx
- src/components/Auth/SignUp.tsx
- src/components/Layout/SaasSelector.tsx
- src/themes/saas/components/input.ts
- src/themes/saas/components/textarea.ts
Removed unnecessary variants in inputs and text area, and I moved the styles from the auth variant to baseStyles so that all inputs/text areas have the same styles. If we need different styles in the future, we will create a variant.
> removed unnecessary variants

- src/components/Navbar/SaasNavbar.tsx
- src/elements/Layout.tsx
It implements the landing page navbar for saas.
It only shows a button instead of the vocdoni app login modal an menus: if not authenticated it redirects to login page, else, to dashboard. 
Any functionality more.
> Implement saas landing navbar

- src/components/OrganizationSaas/Dashboard/Layout.tsx
- src/router/Router.tsx
- src/router/SaasProtectedRoutes.tsx
atm it only permit to enter to the process creation form without wagmi connected (only with the signer)
> Enable create process logic

- src/components/Auth/api.ts
- src/components/Auth/useAuthProvider.ts
- src/components/Layout/ErrorComponent.tsx
- src/components/OrganizationSaas/Dashboard/Team.tsx
It implements team members list
> Implement members list

- .github/workflows/netlify.yml
- src/components/Auth/SignUp.tsx
- src/components/Layout/SaasSelector.tsx
- src/themes/saas/components/Saas/Wapper/index.tsx
removed max width dashboard layout.
closes #760
> removed max width dashboard

- src/components/Auth/ForgotPassword.tsx
- src/components/Auth/SignIn.tsx
- src/components/Auth/SignUp.tsx
- src/components/Auth/Verify.tsx
- src/elements/LayoutAuth.tsx
Auth flex wrapper (signin, signup, forgot password, and verify) moved to LayoutAuth with the proper title and subtitle, setting the title and subtitle using the setters from outlet context
> LayoutAuth wrapper and title, subtitle setter

- src/components/Account/Layout.tsx
- src/components/Auth/ForgotPassword.tsx
- src/components/Auth/SignIn.tsx
- src/components/Auth/SignUp.tsx
- src/components/Layout/InputBasic.tsx
- src/components/Layout/InputPassword.tsx
- src/components/Organization/Dashboard/Invite.tsx
- src/components/ProcessCreate/Meta.tsx
Split InputCustom in InputPassword and InputBasic to simplified the logic
> InputBasic and InputPassword

- src/components/Auth/SignIn.tsx
- src/components/Auth/api.ts
- src/components/Auth/authQueries.ts
Related to topics 2 & 4 from https://github.com/vocdoni/interoperability/issues/234
> Resend verify code if out of date and trying to login

- src/elements/LayoutAuth.tsx
> Layout account refactor

- src/theme/colors.ts
- src/theme/components/tag.ts
- src/theme/index.ts
applied Tags figma styles
closes #851
> Tags figma 

- src/theme/components/badge.ts
applied figma styles
closes #852
> badge figma

- package.json
- src/components/Faucet/Claim.tsx
- src/components/Organization/Create.tsx
- src/components/Organization/Edit.tsx
- src/components/Organization/NoOrganizations.tsx
- src/components/Process/ActionsMenu.tsx
- src/components/ProcessCreate/Census/Gitcoin/StampsUnionType.tsx
- src/components/ProcessCreate/CostPreview.tsx
- src/components/ProcessCreate/Steps/Checks.tsx
- src/components/ProcessCreate/Steps/Confirm.tsx
- src/components/ProcessCreate/Steps/TabsPage.tsx
- yarn.lock
This required creating a new version for `@vocdoni/ui-components`, since they changed the way packages were bundled and distributed.
> Upgrade chakra to latest V2

- src/components/Account/Edit.tsx
- src/components/Process/View.tsx
- src/theme/components/Tabs.ts
> tabs styles

- src/components/Dashboard/Menu/Item.tsx
- src/components/ProcessCreate/Steps/Navigation.tsx
Changed buttons variants from tertiary to transparent
closes #888
> Buttons variant transparent

- src/theme/colors.ts
Updated the dashboard background color in dark mode
closes #882
> dashboard bg color

- src/components/Process/Header.tsx
- src/theme/colors.ts
Fixed the issue with the 'Read More' process in dark mode.
closes #877
> Readmore process 

- src/components/Dashboard/ProcessView.tsx
- src/components/Process/Features.tsx
Also fixed an issue with how votes were shown, and removed the unimplemented "generate results PDF" button
> Process (admin) view features

- src/components/ProcessCreate/Questions/ApprovalVoting.tsx
- src/components/ProcessCreate/Questions/Question.tsx
- src/components/ProcessCreate/Questions/Questions.tsx
- src/components/ProcessCreate/Questions/SingleChoice.tsx
Applied question number styles.
closes #886
> Number 1 Questions step

- src/components/ProcessCreate/Steps/TabsPage.tsx
- src/theme/components/Tabs.ts
DetailedCheckboxes questions styles
> questions detailed checkboxes styles

- src/components/Account/Menu.tsx
> Dashboard menu

- src/components/Auth/api.ts
- src/components/Organization/Subscription.tsx
closes https://github.com/vocdoni/interoperability/issues/225
> Link "change" button in subscription to open a stripe customer portal

- src/components/Auth/SignUp.tsx
- src/components/Auth/Verify.tsx
- src/elements/account/verify.tsx
- Merge verify components into a single unified component
- Update verify page to handle both URL params and manual entry
- Modify signup flow to redirect to verify page instead of inline form
- Remove the develop verify button (which wasn't working anymore)
closes #840
> Unify verification process

- src/components/Account/AccountTypes.ts
- src/components/Auth/api.ts
- src/components/Layout/SaasSelector.tsx
- src/components/Layout/Uploader.tsx
- src/components/Organization/Create.tsx
- src/components/Organization/Edit.tsx
- src/components/Organization/Form.tsx
- src/elements/LayoutDashboard.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
Requires https://github.com/vocdoni/saas-backend/pull/34 to be merged and deployed in order to work.
> Organization file uploaders

- src/components/Dashboard/Menu/Item.tsx
- src/components/Dashboard/Menu/Options.tsx
- src/theme/components/button.ts
Dashboard menu active styles and fixed issues color scheme gray
> Dashboard menu styles

- src/components/Pricing/Card.tsx
- src/components/Pricing/ComparisonTable.tsx
- src/components/Pricing/FeaturesBox.tsx
- src/components/Pricing/Plans.tsx
- src/components/Pricing/SubscriptionPayment.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
> Plans Component Improvements

- src/components/Auth/PasswordForgotForm.tsx
fixed styles recovery password, font sizes and button variant.
closes #910
> fixed styles recovery password

- src/components/Dashboard/ProcessView.tsx
- src/elements/LayoutDashboard.tsx
- src/theme/colors.ts
- src/theme/components/accordion.ts
- src/theme/components/button.ts
- src/theme/components/tag.ts
voting process details styles
closes #908
> voting process details styles

- src/elements/LayoutAuth.tsx
- src/router/SuspenseLoader.tsx
- src/router/routes/auth.tsx
fixed style issues for the aside banner in the auth layout
> Auth layout aside banner

- src/components/Pricing/FeaturesBox.tsx
- src/components/Pricing/PlanUpgrade.tsx
- src/i18n/locales/en.json
- src/i18n/locales/es.json
Applied invite modal styles as required
closes #924
> invite modal styles 

- src/elements/LayoutAuth.tsx
improved layout auth structure
> layout auth

- src/components/Account/Menu.tsx
fixed issue button cannot appear as a descendant button
> button as a descendent button

- src/components/Home/CreateProcess.tsx
Fixed issue icon styles and delete unsued text
> home create process helper

- src/theme/colors.ts
- src/theme/components/alert.ts
Fixed toast styles color issue
> toast styles

- src/i18n/components.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
Added confirm.cancel_button translation and aligned modal footer buttons.
closes #959
> confirm.cancel_button translation

- src/components/Dashboard/Menu/index.tsx
- src/components/Dashboard/ProcessView.tsx
- src/elements/LayoutDashboard.tsx
Positioned the "New Voting" and "Logout" buttons in the dashboard aside with position: sticky at the bottom, and the dashboard background issue fixed.
> Dashboard aside buttons sticky and background

- src/theme/components/modal.ts
aligned buttons modal footer.
to
> aligned buttons modal footer

- src/components/ProcessCreate/Settings/Calendar.tsx
- Add subscription max duration validation
- Show warning alert when duration exceeds plan limit
**Doubts:**
- Should I show the upgrade button somehow?
- Should I validate the value in the step form so people cannot get to the next step if the max duration is exceeded?
> feat: add max duration validation to calendar component

- src/components/Auth/useAuthProvider.ts
- src/components/Dashboard/Menu/OrganizationSwitcher.tsx
- src/components/Organization/Create.tsx
- src/components/Organization/NoOrganizations.tsx
- src/elements/account/createOrganization.tsx
Orgs != suborgs. This is the expected behavior.
Cannot reproduce it, maybe due to some of the changes I've done due to issues down below.
Cannot do much here... everything I tried works, but it's true that sometimes this does not show the name, but the address... that's the fallback in case the network fails, so I cannot do much, other than retrying _ad eternum_, maybe
Nothing can be done here, sorry. Most errors in that screen are 404, which are normal since you're creating an account and needs to check until it's created.
Fixed, but my fixes now do not show the organization name, so I'd like to fine-tune this (this is why it's set as WIP).
Cannot reproduce 😕 
Fixed.
closes #960
> WIP Org fixes

- src/theme/components/stepper.ts
Active step  color and font weight.
closes #974
> Active step

- src/components/Dashboard/Menu/Item.tsx
- src/components/Dashboard/Menu/Options.tsx
Improved the dashboard menu buttons as the underline variant was applied when it should be transparent, and vice versa. Also, submenus now close when clicking outside of them.
> improved dsahboard menu buttons

- src/i18n/locales/en.json
- src/i18n/locales/es.json
- Added missing translations
- Improved translations to make them more concise and short
> Added missing translations.

- src/elements/dashboard/processes/index.tsx
Removed filter buttons when there are no elections.
closes #1005
> filter processes list

- src/components/Dashboard/Menu/Options.tsx
- src/components/Dashboard/Menu/OrganizationSwitcher.tsx
- src/components/ProcessCreate/Steps/index.tsx
- src/elements/LayoutDashboard.tsx
> dashboard issues

- src/components/Dashboard/Menu/OrganizationSwitcher.tsx
Render always the button Add a new organization in OrganizationSwitcher
> Add a new organization button

- src/components/Auth/api.ts
- src/components/Layout/SaasSelector.tsx
- src/components/Organization/Dashboard/Support.tsx
- src/components/Organization/Form.tsx
- src/components/Organization/Invite.tsx
- src/components/Organization/Team.tsx
- src/constants/index.ts
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/queries/account.ts
- src/queries/keys.ts
- src/queries/organization.ts
Adding the buttons for changing role, removing member and resend/cancel invitation
> feat(team): Adding team actions

- src/components/Process/Create/Sidebar/CensusCreation.tsx
- src/components/ProcessCreate/Census/Spreadsheet/Preview.tsx
- src/components/ProcessCreate/Census/Web3.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
This follow-up addresses missing i18n keys overlooked in #1075. It ensures all required translations are now included.
refs #1082
> Follow-up for #1075: Added missing translations

- src/components/Editor/index.tsx
- src/components/Process/Census/Spreadsheet/index.tsx
- src/components/Process/Create/MainContent/Questions/QuestionForm.tsx
- src/components/Process/Create/index.tsx
> feat: Drafts

- src/components/Auth/SignIn.tsx
> fix: Add loading state to submit button during login process

- package.json
- public/default/index.html
- src/components/Calculator/index.tsx
- yarn.lock
We need this GTM script to track behavior and also the Google AdWords performance.
> Added Google Tag Manager (GTM) script

- src/components/Memberbase/Members/index.tsx
- src/components/Organization/Dashboard/index.tsx
- src/components/Process/Create/Sidebar/index.tsx
- src/components/shared/Dashboard/Contents.tsx
- src/theme/components/button.ts
> ui/ux follow-up

- src/components/Memberbase/GroupsBoard.tsx
- src/components/Memberbase/Members/Import.tsx
- src/components/Memberbase/Members/index.tsx
- src/components/Memberbase/TableProvider.tsx
- src/components/Process/Create/Sidebar/VoterAuthentication.tsx
- src/components/Process/TemplateProvider.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/queries/groups.ts
> Implement member add/remove functionality for groups

- src/components/Process/Create/Sidebar/ExtraConfig.tsx
- src/components/Process/Dashboard/ProcessView.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
(to the details section in the sidebar)
> chore(dashboard process view): add process results type

- src/components/Process/Dashboard/ProcessView.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
Awaiting for @ferranrego input on this (if you're OK with the changes simply say it!)
> chore: minor translation changes

- src/components/Organization/View.tsx
> fix: pagination error in accounts

- src/components/Process/Aside.tsx
- src/components/Process/CSP/Step1.tsx
- src/components/Process/ConfirmVoteModal.tsx
- src/components/Process/CreatedBy.tsx
- src/components/Process/Date.tsx
- src/components/Process/Header.tsx
- src/components/Process/View.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/theme/components/spreadsheetAccess.ts
This PR **refactors the public voting page** to align it with the latest designs and the design system. It does **not** change the vote flow or business logic—focus is on **structure, styling, and visual consistency**.
- **Color tokens:** finalize and centralize color definitions.
- **Participatory Budgeting (PB):** re-check visuals once **#1146** is resolved.
- **Multi-choice counter (“1/3”):** needs state exposed from `ui-components` (maybe it's possible but I didn't found how)
- Blocked/affected by: **#1146** (PB bug)
> refactor: Public voting page

- src/components/Process/View.tsx
> fix(ProcessView): Fix weird behaviour with process video

- src/components/Process/Create/MainContent/Questions/QuestionType.tsx
> fix(QuestionType): Ensure menu opens over delete buttons

- src/components/Process/Create/VoterAuthentication/SummaryDisplay.tsx
- src/components/Process/Create/VoterAuthentication/index.tsx
- src/components/Process/Create/index.tsx
> feature: Add summary box for auth config

- src/components/shared/Dashboard/Menu/Options.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
> chore(menu options): Remove unused menu items

- src/components/Process/Create/MainContent/Questions/QuestionForm.tsx
- src/components/Process/Create/MainContent/Questions/index.tsx
> fix: Delete questions error

- src/elements/Layout.tsx
- src/elements/LayoutAuth.tsx
> chore: Fix background inconsistency with Tabs

- src/components/Process/Aside.tsx
- src/components/Process/CSP/CSPAuthModal.tsx
- src/components/Process/CSP/Step1.tsx
- src/theme/components/spreadsheetAccess.ts
> chore: Update button color scheme to black for consistency

- src/components/shared/Navbar/index.tsx
- src/router/routes/root.tsx
> feat(Navbar): Delete navbar items for public voting page

- src/components/Memberbase/Members/Import.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
closes #1109 
depends on https://github.com/vocdoni/saas-backend/pull/207
> feat: Improve import errors handling

- src/components/Process/CSP/Step0.tsx
- src/components/Process/Create/MainContent/QuestionType.tsx
- src/components/Process/Create/MainContent/SelectionLimits.tsx
- src/components/Process/Create/TemplateProvider.tsx
- src/components/Process/Create/common.ts
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
> fix: Small fixes for participatory budgeting template

- src/components/Memberbase/Members/index.tsx
- src/components/Organization/Address.tsx
- src/constants/index.ts
The export button has been removed until the section is properly coded
closes #740
> chore: fix explorer links + remove export button

- src/components/Process/Create/Sidebar/BasicConfig.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
> chore(calendar): Update max duration exceeded message

- src/components/Process/Dashboard/ProcessView.tsx
- yarn.lock
closes #1238
closes #1218 thanks to the package upgrade and [this change](https://github.com/vocdoni/ui-components/commit/40ece0a605e9c26d1826e4ac986c742f4e66df01)
refs #1195
> chore(dashboard process view): force results render

- src/components/Process/CSP/Step0.tsx
- src/components/Process/CSP/basics.tsx
- src/components/Process/View.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
> chore: Voting page minor changes

- src/components/Process/Create/MainContent/QuestionType.tsx
- src/components/Process/Create/MainContent/index.tsx
- src/components/Process/Create/Sidebar/CensusCreation.tsx
- src/components/Process/Create/Sidebar/ExtraConfig.tsx
- src/components/Process/Create/common.ts
- src/components/Process/Create/index.tsx
- src/components/Process/Dashboard/ProcessView.tsx
- src/components/shared/Form/Select.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/utils/analytics.ts
> chore: Question Type selector changes

- src/components/Auth/SignIn.tsx
> chore(oauth): disable temporarily

- src/components/Organization/Dashboard/Support.tsx
- src/components/Pricing/Features.tsx
- src/components/Process/Create/index.tsx
- src/components/shared/Layout/SubscriptionLockedContent.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
closes #1252 
This could be a follow-up:
> chore(ProcessCreate): Change how video is displayed

- .env.example
- src/components/Account/Edit.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/importmeta.d.ts
- vite.config.ts
> feat(Account): Replaced support email copy with contact us button

- src/components/shared/Dashboard/Menu/UserProfile.tsx
> chore(UserProfile): Show organization avatar on profile

- src/components/Process/Aside.tsx
- src/components/Process/LogoutButton.tsx
- src/i18n/components.tsx
- src/i18n/locales/ca.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
> feat: Add logout for all census types
